version: '3.9'
services:
  db:
    image: postgres:15
    container_name: tmp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: tmp-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata:
